name: Vividus Documentation Deployment

on:
  pull_request:
    branches:
    - master
  env:
    ERROR: ''

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 12.18.1
    - run: npm i -g @antora/cli antora-site-generator-lunr
    - run: npm install -g gitlab:antora/xref-validator
    - run: DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr DOCSEARCH_INDEX_VERSION=latest NODE_PATH="$(npm -g root)" antora --generator antora-site-generator-lunr ./antora-playbook.yml

    - name: Antora links check
      shell: bash
    - run: ls | touch file
    - run: |
        `antora --generator @antora/xref-validator antora-playbook.yml | grep "\"refname\":\"master\""` > file
        ERROR="`cat file`"
        if [[ -z "$ERROR" ]]; then 
          echo "No errors found"; 
        else 
          echo "$ERROR"; 
          exit 3; 
        fi
